### PR TITLE
readme: add Nix instructions

### PR DESCRIPTION
**Pull request by srid**

### CODE REVIEW

**Comment by jtdaugherty** [comment]
Thanks for the patch, but I'm going to decline to merge it since I'm not going to support Nix explicitly.

**Comment by srid** [comment]
@jtdaugherty I only opened this PR, because you asked me to here:

https://github.com/jtdaugherty/tart/pull/18#issuecomment-1270594600

> Is there any way this functionality could be kept somewhere outside the repo and still be useful? If that were possible, I'd be happy to link to a third-party repo from the README about it, for example.

**Comment by jtdaugherty** [comment]
Ah, I see. Sorry about the confusion. I'd be okay with adding a note to the README if *all* it did was point to some place where those instructions were kept, because it's the instructions that I can't maintain. The change in this pull request adds more detail than I want to have in the README which is why I declined it. The change links to a project on which the instructions are based, not a place where the instructions in this patch are kept.

**Comment by srid** [comment]
That's fair.

**Pull request closed without merging**
